version: '3.9'
services:
    user_service_db:
        image: postgres:latest
        container_name: user_service_db
        ports:
              - 54321:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: user_service_db
    tweet_service_db:
        image: postgres:latest
        container_name: tweet_service_db
        ports:
              - 54322:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: tweet_service_db
    interaction_service_db:
        image: postgres:latest
        container_name: interaction_service_db
        ports:
              - 54323:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: interaction_service_db
    redis:
        image: redis:latest
        container_name: redis
        ports:
              - 63790:6379
 #    kafka:
 #        image: bitnami/kafka:latest
 #        container_name: kafka
 #        ports:
 #            - 19092:9092
 #        environment:
 #            KAFKA_ENABLE_KRAFT: yes
 #            KAFKA_CFG_PROCESS_ROLES: broker,controller
 #            KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
 #            KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
 #            KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
 #            KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
 #            # - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
 #            # - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
 #            # - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
 #            KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: true
 #            KAFKA_BROKER_ID: 1
 #            KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
 #            ALLOW_PLAINTEXT_LISTENER: yes
 # 