#!/usr/bin/env bash
# Force the C locale so printf '%f' parses period-decimal coverage ratios (e.g. 0.95)
# regardless of the host LC_NUMERIC — a comma locale otherwise mangles them to 0,0000.
export LC_ALL=C
#
# coverage-gate.sh — assert JaCoCo line + branch coverage ≥ 90 % per service module.
#
# Two modes:
#   unit       — read each service's `target/site/jacoco/jacoco.csv` produced by
#                `mvn verify` from unit tests + JaCoCo `report` execution. This
#                is the load-bearing FE acceptance gate ("≥ 90 % line + branch
#                coverage from unit tests alone").
#   cucumber   — generate per-service reports from the .exec files dumped from
#                the FE service JVMs into
#                testing-results/functional-equivalence/jacoco/<stack>/, then
#                check the FE black-box boundary denominator. HTTP-unreachable
#                boot-time/fault-injection/config internals are filtered in this
#                mode so gateway-driven behavior can be held to the same 90 %
#                line + branch threshold.
#
# Usage:
#     ./testing/functional-equivalence/coverage-gate.sh unit [<stack>]
#     ./testing/functional-equivalence/coverage-gate.sh cucumber <stack>
#
# `<stack>` is `async` or `reactive`; defaults to both.
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
THRESHOLD="${COVERAGE_THRESHOLD:-0.90}"
JACOCO_VERSION="0.8.12"
JACOCO_CLI_JAR="$HOME/.m2/repository/org/jacoco/org.jacoco.cli/${JACOCO_VERSION}/org.jacoco.cli-${JACOCO_VERSION}-nodeps.jar"

SERVICES=(gateway-service user-service tweet-service interaction-service)

# JaCoCo's Maven report execution applies these structural excludes itself.
# The standalone CLI used for Cucumber .exec aggregation does not, so cucumber
# mode strips the same generated/no-logic bytecode before report generation.
COMMON_CLASS_EXCLUDES=(
    "*/model/*"
    "*/entity/*"
    "*MapperImpl.class"
    "*Application.class"
)

# Cucumber runs the platform as a black-box, through the gateway. Its coverage
# signal is therefore the HTTP boundary: service controllers plus deterministic
# gateway policy helpers that can be driven from feature files.
# Unit coverage remains the gate for business internals.
#
# These class-level excludes remove implementation denominators that either
# cannot be targeted meaningfully from gateway-level features or are already
# covered by the unit gate: business services, repositories, caches, internal
# clients/failure arms, mappers, exception plumbing, utility helpers, metrics,
# framework wiring, route-construction/rate-limit plumbing, schedulers,
# boot-time AI mock calibration, and the benchmark-only AI controller.
CUCUMBER_BOUNDARY_CLASS_EXCLUDES=(
    "*/service/*"
    "*/repository/*"
    "*/cache/*"
    "*/client/*"
    "*/mapper/*"
    "*/exception/*"
    "*/util/*"
    "*/metrics/*"
    "*/controller/AiController.class"
    "*/config/ObservationConfiguration.class"
    "*/config/MetricConfiguration.class"
    "*/config/HttpClientConfiguration.class"
    "*/config/HttpClientMtlsConfiguration.class"
    "*/config/OpenApiConfig.class"
    "*/config/ActuatorSecurityConfig.class"
    "*/config/JacksonConfiguration.class"
    "*/config/MvcAsyncConfig.class"
    "*/config/CacheConfiguration*.class"
    "*/config/PasswordEncoderConfiguration.class"
    "*/config/ReactivePoolConfiguration*.class"
    "*/config/RetryConfiguration.class"
    "*/config/ThreadConfiguration*.class"
    "*/config/AiConfiguration*.class"
    "*/config/BoundedElasticMetrics*.class"
    "*/config/RateLimiterConfiguration.class"
    "*/config/GatewayRoutesConfiguration.class"
)

usage() {
    cat <<EOF
Usage: $0 <unit|cucumber> [<async|reactive>]

unit:        read target/site/jacoco/jacoco.csv (must be generated by `mvn verify` first)
cucumber:    aggregate testing-results/functional-equivalence/jacoco/<stack>/<service>.exec into reports + check

Threshold:   line + branch ≥ ${THRESHOLD} (override via COVERAGE_THRESHOLD env)
EOF
}

# Returns "line_ratio branch_ratio" for the given jacoco.csv path.
parse_csv() {
    local csv="$1"
    awk -F, '
        NR == 1 { for (i = 1; i <= NF; i++) col[$i] = i; next }
        {
            bm += $col["BRANCH_MISSED"]; bc += $col["BRANCH_COVERED"];
            lm += $col["LINE_MISSED"];   lc += $col["LINE_COVERED"];
        }
        END {
            line   = (lm + lc == 0) ? 1.0 : lc / (lm + lc);
            branch = (bm + bc == 0) ? 1.0 : bc / (bm + bc);
            printf "%.4f %.4f\n", line, branch;
        }
    ' "$csv"
}

check_one() {
    local label="$1" csv="$2"
    if [[ ! -f "$csv" ]]; then
        printf '%-50s NO_REPORT (expected at %s)\n' "$label" "$csv"
        return 2
    fi
    # A header-only csv means JaCoCo recorded no classes (e.g. everything excluded, or
    # tests did not run). Treat that as a hard failure — NOT 100% — so an empty report can
    # never masquerade as full coverage.
    if [[ "$(grep -c -v '^GROUP,' "$csv")" -eq 0 ]]; then
        printf '%-50s NO_DATA (empty report — nothing measured)\n' "$label"
        return 1
    fi
    read -r line branch < <(parse_csv "$csv")
    local line_ok branch_ok
    line_ok=$(awk -v l="$line" -v t="$THRESHOLD" 'BEGIN { print (l >= t) ? "PASS" : "FAIL" }')
    branch_ok=$(awk -v b="$branch" -v t="$THRESHOLD" 'BEGIN { print (b >= t) ? "PASS" : "FAIL" }')
    if [[ "$line_ok" == "PASS" && "$branch_ok" == "PASS" ]]; then
        printf '%-50s line=%.4f branch=%.4f PASS\n' "$label" "$line" "$branch"
        return 0
    else
        printf '%-50s line=%.4f branch=%.4f FAIL\n' "$label" "$line" "$branch"
        return 1
    fi
}

ensure_cli_jar() {
    if [[ ! -f "$JACOCO_CLI_JAR" ]]; then
        echo "Fetching jacoco-cli ${JACOCO_VERSION} into local Maven repo…"
        ( cd "$REPO_ROOT/testing/functional-equivalence" && ./mvnw -B dependency:get \
            -Dartifact="org.jacoco:org.jacoco.cli:${JACOCO_VERSION}:jar:nodeps" \
            -Dtransitive=false ) >/dev/null
    fi
    if [[ ! -f "$JACOCO_CLI_JAR" ]]; then
        echo "ERROR: jacoco-cli not available at $JACOCO_CLI_JAR" >&2
        exit 3
    fi
}

matches_any_pattern() {
    local rel="$1"
    shift
    local pattern
    for pattern in "$@"; do
        if [[ "$rel" == $pattern ]]; then
            return 0
        fi
    done
    return 1
}

strip_classes() {
    local classes_dir="$1"
    shift
    local class_file rel
    while IFS= read -r -d '' class_file; do
        rel="${class_file#"$classes_dir"/}"
        if matches_any_pattern "$rel" "$@"; then
            rm -f "$class_file"
        fi
    done < <(find "$classes_dir" -type f -name '*.class' -print0)
}

# Generate per-service Cucumber-coverage reports from the .exec files the
# in-container JaCoCo agent produced during the FE suite, then run the same
# CSV-based threshold check.
#
# IMPORTANT: the in-container JaCoCo agent records coverage against classes
# loaded from BOOT-INF/classes inside Spring Boot's repackaged JAR. The host's
# target/classes/ directory has DIFFERENT bytecode hashes for the same classes
# (different Maven 3.9.9 in Docker vs 3.9.10 on host, or javac variations) —
# JaCoCo CLI fails to match them and reports 0 % for affected classes.
# Workaround: extract BOOT-INF/classes from the docker image into a temp dir
# and use THOSE as --classfiles.
gen_cucumber_report() {
    local stack="$1" svc="$2"
    local exec_file="$REPO_ROOT/testing-results/functional-equivalence/jacoco/${stack}/${svc}.exec"
    local out_dir="$REPO_ROOT/testing-results/functional-equivalence/jacoco-report/${stack}/${svc}"
    local classes_dir="$out_dir/extracted-classes"

    if [[ ! -f "$exec_file" ]]; then
        printf '%-50s NO_EXEC (expected at %s)\n' "${stack}/${svc}" "$exec_file"
        return 2
    fi

    # Extract BOOT-INF/classes from the docker image's app.jar.
    rm -rf "$classes_dir"
    mkdir -p "$classes_dir" "$out_dir"
    # W14 image naming: ${IMAGE_PREFIX}-<svc>-<stack>:${TAG} (e.g. tweebyte-user-service-async:local).
    local image="${IMAGE_PREFIX:-tweebyte}-${svc}-${stack}:${TAG:-local}"
    if ! docker image inspect "$image" >/dev/null 2>&1; then
        echo "ERROR: docker image $image missing — bring functional-equivalence up at least once first" >&2
        return 3
    fi
    local cid
    cid=$(docker create "$image" 2>/dev/null) || {
        echo "ERROR: could not create probe container from $image" >&2
        return 3
    }
    docker cp "$cid:/app/app.jar" "$classes_dir/app.jar" >/dev/null 2>&1
    docker rm "$cid" >/dev/null 2>&1
    (cd "$classes_dir" && unzip -q app.jar 'BOOT-INF/classes/*' && mv BOOT-INF/classes/* . && rm -rf BOOT-INF app.jar) || {
        echo "ERROR: could not extract BOOT-INF/classes from $image" >&2
        return 3
    }

    strip_classes "$classes_dir" "${COMMON_CLASS_EXCLUDES[@]}" "${CUCUMBER_BOUNDARY_CLASS_EXCLUDES[@]}"

    if ! java -jar "$JACOCO_CLI_JAR" report "$exec_file" \
        --classfiles "$classes_dir" \
        --csv "$out_dir/jacoco.csv" \
        --xml "$out_dir/jacoco.xml" \
        --html "$out_dir" \
        --name "$stack/$svc Cucumber" \
        --quiet; then
        printf '%-50s BAD_EXEC (could not parse %s)\n' "${stack}/${svc} (cucumber)" "$exec_file"
        return 1
    fi
    check_one "${stack}/${svc} (cucumber)" "$out_dir/jacoco.csv"
}

mode="${1:-}"
stack_filter="${2:-}"
case "$mode" in
    unit|cucumber) ;;
    *) usage; exit 1 ;;
esac

stacks=()
case "$stack_filter" in
    async|reactive) stacks+=("$stack_filter") ;;
    "") stacks=(async reactive) ;;
    *) usage; exit 1 ;;
esac

OVERALL=0
case "$mode" in
    unit)
        for stack in "${stacks[@]}"; do
            for svc in "${SERVICES[@]}"; do
                csv="$REPO_ROOT/backend/${stack}/${svc}/target/site/jacoco/jacoco.csv"
                check_one "${stack}/${svc} (unit)" "$csv" || OVERALL=$?
            done
        done
        ;;
    cucumber)
        ensure_cli_jar
        for stack in "${stacks[@]}"; do
            for svc in "${SERVICES[@]}"; do
                gen_cucumber_report "$stack" "$svc" || OVERALL=$?
            done
        done
        ;;
esac

if (( OVERALL == 0 )); then
    echo "OVERALL: PASS (all modules ≥ ${THRESHOLD} line + branch)"
elif (( OVERALL == 2 )); then
    echo "OVERALL: PARTIAL (some reports missing — see NO_REPORT lines above)"
    exit 2
else
    echo "OVERALL: FAIL"
    exit 1
fi
