/*
 * Copyright 2026 Tweebyte contributors
 * SPDX-License-Identifier: MIT
 */

package ro.tweebyte.tweetservice.repository;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.Objects;
import java.util.UUID;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

import lombok.RequiredArgsConstructor;
import org.springframework.r2dbc.core.DatabaseClient;
import reactor.core.publisher.Flux;

import ro.tweebyte.tweetservice.entity.HashtagEntity;

/**
 * {@link DatabaseClient} batched implementation of the missing-hashtag insert. Binds id +
 * text per row as positional parameters (injection-safe) and short-circuits on an empty
 * collection. The id is client-generated (as {@code HashtagMapper.mapTextToEntity}
 * already supplies), matching the UUID-PK + {@code Persistable} insert semantics the
 * per-row {@code save} relied on.
 *
 * @author Andrei Zbarcea
 */
@RequiredArgsConstructor
public class HashtagRepositoryCustomImpl implements HashtagRepositoryCustom {

	private final DatabaseClient databaseClient;

	@Override
	public Flux<HashtagEntity> insertAll(Collection<HashtagEntity> hashtags) {
		if (hashtags.isEmpty()) {
			return Flux.empty();
		}
		List<HashtagEntity> rows = new ArrayList<>(hashtags);
		String valuesClause = IntStream.range(0, rows.size())
			.mapToObj(i -> "(:id" + i + ", :text" + i + ")")
			.collect(Collectors.joining(", "));
		DatabaseClient.GenericExecuteSpec spec = this.databaseClient
			.sql("INSERT INTO hashtags (id, text) VALUES " + valuesClause);
		for (int i = 0; i < rows.size(); i++) {
			HashtagEntity row = rows.get(i);
			// Both columns are NOT NULL; the id is client-generated by HashtagMapper and the
			// text is the parsed token. requireNonNull documents the invariant DatabaseClient.bind
			// relies on (it rejects nulls — bindNull would be needed otherwise).
			UUID id = Objects.requireNonNull(row.getId(), "hashtag id must be set before insert");
			String text = Objects.requireNonNull(row.getText(), "hashtag text must be set before insert");
			spec = spec.bind("id" + i, id).bind("text" + i, text);
		}
		return spec.then().thenMany(Flux.fromIterable(rows));
	}

}
