# Server configuration
server.port=${SERVER_PORT:9093}
server.error.include-stacktrace=never
server.error.include-message=always

spring.main.allow-circular-references=true

# Database configuration
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:54323}/interaction_service_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# Hibernate configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Security configuration
app.security.jwt.keystore-location=keystore.jks
app.security.jwt.keystore-password=password
app.security.jwt.key-alias=tweebyte

# Thread configuration
app.concurrency.interaction.custom-thread-pool=true

# Cache configuration
spring.data.redis.host=localhost
spring.data.redis.port=${CACHE_PORT:26379}

# Client configuration
app.user.base-url=http://localhost:9091/
app.tweet.base-url=http://localhost:9092/

spring.jpa.properties.hibernate.jdbc.batch_size=50

spring.datasource.hikari.maximum-pool-size=150
spring.datasource.hikari.minimum-idle=75
spring.datasource.hikari.connection-timeout=3000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.leak-detection-threshold=60000

spring.datasource.hikari.auto-commit=false

spring.data.redis.lettuce.pool.enabled=true
spring.data.redis.lettuce.pool.max-active=600
spring.data.redis.lettuce.pool.max-idle=300
spring.data.redis.lettuce.pool.min-idle=150
spring.data.redis.lettuce.pool.max-wait=1000ms
spring.data.redis.lettuce.pool.time-between-eviction-runs=30s

spring.data.redis.timeout=1000ms

spring.cache.type=redis
spring.cache.redis.time-to-live=60s

management.endpoints.web.exposure.include=prometheus,health,info