#!/usr/bin/env bash
#
# coverage-gate.sh — assert JaCoCo line + branch coverage ≥ 90 % per service module.
#
# Two modes:
#   unit       — read each service's `target/site/jacoco/jacoco.csv` produced by
#                `mvn verify` from unit tests + JaCoCo `report` execution. This
#                is the load-bearing FE acceptance gate ("≥ 90 % line + branch
#                coverage from unit tests alone").
#   cucumber   — generate per-service reports from the .exec files written
#                inside service containers during the FE Cucumber run (the
#                fe-test.yml overlay bind-mounts /jacoco-out to
#                testing-results/equivalence/jacoco/), then check those. This
#                runs in advisory mode — see AGENTS.md for the structural
#                ceilings on cucumber-only coverage.
#
# Usage:
#     ./infrastructure/coverage-gate.sh unit [<stack>]
#     ./infrastructure/coverage-gate.sh cucumber <stack>
#
# `<stack>` is `async` or `reactive`; defaults to both.
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
THRESHOLD="${COVERAGE_THRESHOLD:-0.90}"
JACOCO_VERSION="0.8.12"
JACOCO_CLI_JAR="$HOME/.m2/repository/org/jacoco/org.jacoco.cli/${JACOCO_VERSION}/org.jacoco.cli-${JACOCO_VERSION}-nodeps.jar"

SERVICES=(gateway-service user-service tweet-service interaction-service)

usage() {
    cat <<EOF
Usage: $0 <unit|cucumber> [<async|reactive>]

unit:        read target/site/jacoco/jacoco.csv (must be generated by `mvn verify` first)
cucumber:    aggregate testing-results/equivalence/jacoco/<service>.exec into reports + check

Threshold:   line + branch ≥ ${THRESHOLD} (override via COVERAGE_THRESHOLD env)
EOF
}

# Returns "line_ratio branch_ratio" for the given jacoco.csv path.
parse_csv() {
    local csv="$1"
    awk -F, '
        NR == 1 { for (i = 1; i <= NF; i++) col[$i] = i; next }
        {
            bm += $col["BRANCH_MISSED"]; bc += $col["BRANCH_COVERED"];
            lm += $col["LINE_MISSED"];   lc += $col["LINE_COVERED"];
        }
        END {
            line   = (lm + lc == 0) ? 1.0 : lc / (lm + lc);
            branch = (bm + bc == 0) ? 1.0 : bc / (bm + bc);
            printf "%.4f %.4f\n", line, branch;
        }
    ' "$csv"
}

check_one() {
    local label="$1" csv="$2"
    if [[ ! -f "$csv" ]]; then
        printf '%-50s NO_REPORT (expected at %s)\n' "$label" "$csv"
        return 2
    fi
    read -r line branch < <(parse_csv "$csv")
    local line_ok branch_ok
    line_ok=$(awk -v l="$line" -v t="$THRESHOLD" 'BEGIN { print (l >= t) ? "PASS" : "FAIL" }')
    branch_ok=$(awk -v b="$branch" -v t="$THRESHOLD" 'BEGIN { print (b >= t) ? "PASS" : "FAIL" }')
    if [[ "$line_ok" == "PASS" && "$branch_ok" == "PASS" ]]; then
        printf '%-50s line=%.4f branch=%.4f PASS\n' "$label" "$line" "$branch"
        return 0
    else
        printf '%-50s line=%.4f branch=%.4f FAIL\n' "$label" "$line" "$branch"
        return 1
    fi
}

ensure_cli_jar() {
    if [[ ! -f "$JACOCO_CLI_JAR" ]]; then
        echo "Fetching jacoco-cli ${JACOCO_VERSION} into local Maven repo…"
        mvn -B dependency:get \
            -Dartifact="org.jacoco:org.jacoco.cli:${JACOCO_VERSION}:jar:nodeps" \
            -Dtransitive=false \
            >/dev/null
    fi
    if [[ ! -f "$JACOCO_CLI_JAR" ]]; then
        echo "ERROR: jacoco-cli not available at $JACOCO_CLI_JAR" >&2
        exit 3
    fi
}

# Generate per-service Cucumber-coverage reports from the .exec files the
# in-container JaCoCo agent produced during the FE suite, then run the same
# CSV-based threshold check.
#
# IMPORTANT: the in-container JaCoCo agent records coverage against classes
# loaded from BOOT-INF/classes inside Spring Boot's repackaged JAR. The host's
# target/classes/ directory has DIFFERENT bytecode hashes for the same classes
# (different Maven 3.9.9 in Docker vs 3.9.10 on host, or javac variations) —
# JaCoCo CLI fails to match them and reports 0 % for affected classes.
# Workaround: extract BOOT-INF/classes from the docker image into a temp dir
# and use THOSE as --classfiles.
gen_cucumber_report() {
    local stack="$1" svc="$2"
    local exec_file="$REPO_ROOT/testing-results/equivalence/jacoco/${svc}.exec"
    local out_dir="$REPO_ROOT/testing-results/equivalence/jacoco-report/${stack}/${svc}"
    local classes_dir="$out_dir/extracted-classes"

    if [[ ! -f "$exec_file" ]]; then
        printf '%-50s NO_EXEC (expected at %s)\n' "${stack}/${svc}" "$exec_file"
        return 2
    fi

    # Extract BOOT-INF/classes from the docker image's app.jar.
    rm -rf "$classes_dir"
    mkdir -p "$classes_dir" "$out_dir"
    local image="tweebyte-${svc}:latest"
    if ! docker image inspect "$image" >/dev/null 2>&1; then
        echo "ERROR: docker image $image missing — bring fe-test up at least once first" >&2
        return 3
    fi
    local cid
    cid=$(docker create "$image" 2>/dev/null) || {
        echo "ERROR: could not create probe container from $image" >&2
        return 3
    }
    docker cp "$cid:/app/app.jar" "$classes_dir/app.jar" >/dev/null 2>&1
    docker rm "$cid" >/dev/null 2>&1
    (cd "$classes_dir" && unzip -q app.jar 'BOOT-INF/classes/*' && mv BOOT-INF/classes/* . && rm -rf BOOT-INF app.jar) || {
        echo "ERROR: could not extract BOOT-INF/classes from $image" >&2
        return 3
    }

    # Mirror the per-pom JaCoCo excludes — without these, Lombok-heavy DTOs /
    # entities and Spring @Configuration classes contribute hundreds of
    # branches each (equals/hashCode arms etc.) and drag the percentage
    # down. The maven `report` execution applies these implicitly; the
    # standalone CLI does not, so we strip the matching .class files first.
    find "$classes_dir" \
        -path '*/model/*' -name '*.class' -delete -o \
        -path '*/entity/*' -name '*.class' -delete -o \
        -path '*/config/*' -name '*.class' -delete -o \
        -path '*/exception/*' -name '*.class' -delete -o \
        -name '*MapperImpl.class' -delete -o \
        -name '*Application.class' -delete 2>/dev/null

    java -jar "$JACOCO_CLI_JAR" report "$exec_file" \
        --classfiles "$classes_dir" \
        --csv "$out_dir/jacoco.csv" \
        --html "$out_dir" \
        --name "$stack/$svc Cucumber" \
        --quiet
    check_one "${stack}/${svc} (cucumber)" "$out_dir/jacoco.csv"
}

mode="${1:-}"
stack_filter="${2:-}"
case "$mode" in
    unit|cucumber) ;;
    *) usage; exit 1 ;;
esac

stacks=()
case "$stack_filter" in
    async|reactive) stacks+=("$stack_filter") ;;
    "") stacks=(async reactive) ;;
    *) usage; exit 1 ;;
esac

OVERALL=0
case "$mode" in
    unit)
        for stack in "${stacks[@]}"; do
            for svc in "${SERVICES[@]}"; do
                csv="$REPO_ROOT/${stack}/${svc}/target/site/jacoco/jacoco.csv"
                check_one "${stack}/${svc} (unit)" "$csv" || OVERALL=$?
            done
        done
        ;;
    cucumber)
        ensure_cli_jar
        for stack in "${stacks[@]}"; do
            for svc in "${SERVICES[@]}"; do
                gen_cucumber_report "$stack" "$svc" || OVERALL=$?
            done
        done
        ;;
esac

if (( OVERALL == 0 )); then
    echo "OVERALL: PASS (all modules ≥ ${THRESHOLD} line + branch)"
elif (( OVERALL == 2 )); then
    echo "OVERALL: PARTIAL (some reports missing — see NO_REPORT lines above)"
    exit 2
else
    echo "OVERALL: FAIL"
    exit 1
fi
